# Generated by Django 4.0.5 on 2022-11-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('purchased_on', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('tpm_expiry', models.DateField()),
                ('status', models.CharField(choices=[('working', 'working'), ('damaged', 'damaged')], max_length=30)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master.Category.asset_type+', to='master.category')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purchased_on', models.DateField(verbose_name='')),
                ('expiry', models.DateField(verbose_name='')),
                ('installed_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.hardware')),
                ('softwaretype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.softwaretype')),
            ],
        ),
    ]
