# Generated by Django 4.0.5 on 2022-11-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('product', '0003_remove_hardware_asset_type_remove_hardware_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='assetcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.category'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='assettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master.category'),
        ),
    ]
