# Generated by Django 4.0.5 on 2022-11-21 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('product', '0004_alter_hardware_assetcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='assetcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category1', to='master.category'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='assettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_type1', to='master.category'),
        ),
    ]
