# Generated by Django 4.0.5 on 2022-11-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_hardware_assetcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
