# Generated by Django 4.0.5 on 2022-11-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_hardware_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='asset_type',
        ),
    ]
