# Generated by Django 4.0.5 on 2022-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_hardware_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('IT Assets', 'IT Assets'), ('Non IT Assets', 'Non IT Assets')], max_length=50),
        ),
    ]
