# Generated by Django 4.0.5 on 2022-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_hardware_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('IT Assets', 'IT Assets'), ('Non IT Assets', 'Non IT Assets')], default='IT Assets', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('damaged', 'damaged'), ('disposed', 'disposed')], max_length=30),
        ),
    ]
