# Generated by Django 4.0.5 on 2022-11-29 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_alter_hardware_asset_type_alter_hardware_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonitasset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('asset_type', models.CharField(blank=True, choices=[('IT Assets', 'IT Assets'), ('Non IT Assets', 'Non IT Assets')], default='NON IT Assets', max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('purchased_on', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('cost', models.PositiveIntegerField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.branch')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.location')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.vendor')),
            ],
        ),
    ]
